src:
  changed-files:
    - any-glob-to-any-file:
        - src/**
        - tests/**
        - scripts/**
        - pyproject.toml
        - uv.lock
        - index.html

docs:
  changed-files:
    - any-glob-to-any-file:
        - '*.md'
        - assets/**
        - site.webmanifest
        - '*.png'
        - '*.ico'

github:
  changed-files:
    - any-glob-to-any-file:
        - .github/**
