contact_links:
  - name: Are you looking for documentation on simple-topic-modeling?
    url: https://maehr.github.io/simple-topic-modeling
    about: Please see the documentation for simple-topic-modeling on its GitHub Pages page.
  - name: Do want to discuss simple-topic-modeling with the community?
    url: https://github.com/maehr/simple-topic-modeling/discussions
    about: Please see the discussions page for simple-topic-modeling.
blank_issues_enabled: true
